package domain.orchestration;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.Dictionary;
import java.util.List;

@DynamoDBTable(tableName="JobDetail")
@DynamoDBTyped
public class JobDetail {
    private String id;
    private JobType jobType;
    private List<JobDependency> jobDependencies;
    private Dictionary<String, String> params;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public JobType getJobType() {
        return jobType;
    }

    public void setJobType(JobType jobType) {
        this.jobType = jobType;
    }

    @DynamoDBAttribute
    public List<JobDependency> getJobDependencies() {
        return jobDependencies;
    }

    public void setJobDependencies(List<JobDependency> jobDependencies) {
        this.jobDependencies = jobDependencies;
    }

    @DynamoDBAttribute
    public Dictionary<String, String> getParams() {
        return params;
    }

    public void setParams(Dictionary<String, String> params) {
        this.params = params;
    }
}
